#!/usr/bin/env bash
# W-Monitor Linux Installer Script
# Supports agent and hub modes.
#
# Usage:
#   sudo ./install.sh --mode agent --hub-url https://hub:8080 --api-key <key>
#   sudo ./install.sh --mode hub --api-key <key>
#   sudo ./install.sh --mode hub --db postgres --dsn "postgres://user:pass@host/db?sslmode=require" --api-key <key>
set -e

INSTALL_DIR="/usr/local/bin"
EXE_NAME="sysmon"
SOURCE_EXE="./wmonitor_linux"
TARGET_EXE="$INSTALL_DIR/$EXE_NAME"

# Defaults
MODE="agent"
HUB_URL=""
API_KEY=""
DSN=""
DB="sqlite"

# Parse flags
while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode)    MODE="$2";    shift 2 ;;
        --hub-url) HUB_URL="$2"; shift 2 ;;
        --api-key) API_KEY="$2"; shift 2 ;;
        --dsn)     DSN="$2";     shift 2 ;;
        --db)      DB="$2";      shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# 1. Ensure root privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (e.g. sudo ./install.sh)"
  exit 1
fi

# 2. Validate parameters
if [ "$MODE" = "agent" ] && [ -z "$HUB_URL" ]; then
    echo "Error: --hub-url is required for agent mode"
    exit 1
fi
if [ -z "$API_KEY" ]; then
    echo "Error: --api-key is required"
    exit 1
fi
if [ "$MODE" = "hub" ] && [ "$DB" = "postgres" ] && [ -z "$DSN" ]; then
    echo "Error: --dsn is required for hub mode with postgres"
    exit 1
fi

if [ ! -f "$SOURCE_EXE" ]; then
    echo "Error: Cannot find $SOURCE_EXE. Please build first."
    exit 1
fi

# 3. Stop existing service
if systemctl is-active --quiet sysmon 2>/dev/null; then
    echo "Stopping existing sysmon service..."
    systemctl stop sysmon
fi
if systemctl is-enabled --quiet sysmon 2>/dev/null; then
    echo "Uninstalling old service registration..."
    if [ -f "$TARGET_EXE" ]; then
        "$TARGET_EXE" -uninstall || true
    fi
fi

# 4. Copy binary
echo "Copying binary to $INSTALL_DIR..."
cp "$SOURCE_EXE" "$TARGET_EXE"
chmod +x "$TARGET_EXE"

# 5. Write config.env - credentials stored in a locked file, not exposed in process list
CONFIG_DIR="/etc/wmonitor"
CONFIG_FILE="$CONFIG_DIR/config.env"
mkdir -p "$CONFIG_DIR"

{
    echo "# W-Monitor config - DO NOT COMMIT - generated by install.sh"
    echo "WMONITOR_MODE=$MODE"
    echo "WMONITOR_API_KEY=$API_KEY"
    if [ "$MODE" = "agent" ]; then
        echo "WMONITOR_AGENT_HUB=$HUB_URL"
    fi
    if [ "$MODE" = "hub" ] && [ "$DB" = "postgres" ]; then
        echo "WMONITOR_DB_DSN=$DSN"
        echo "WMONITOR_DB=postgres"
    fi
} > "$CONFIG_FILE"

chmod 600 "$CONFIG_FILE"
echo "Config written and locked: $CONFIG_FILE"

# 6. Register and start systemd service
echo "Registering systemd service..."
"$TARGET_EXE" -install

echo "Starting service..."
"$TARGET_EXE" -start

echo ""
if [ "$MODE" = "agent" ]; then
    echo "W-Monitor AGENT installed and started!"
    echo "  Pushing metrics to: $HUB_URL"
    echo "  Config:             $CONFIG_FILE"
else
    echo "W-Monitor HUB installed and started!"
    echo "  Dashboard: http://localhost:8080"
    echo "  DB:        $DB"
    echo "  Config:    $CONFIG_FILE"
fi
echo "Check status: systemctl status sysmon"
echo "View logs:    journalctl -u sysmon -f"
